/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package Parsing;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>TA.flex</tt>
 */
class TALexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STR = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\4\1\6\1\6\1\5\22\0\1\14\1\0\1\10"+
    "\5\0\1\33\1\34\2\0\1\35\3\0\12\3\7\0\32\15\1\1"+
    "\1\0\1\2\1\0\1\7\1\0\2\15\1\22\4\15\1\23\1\20"+
    "\1\27\1\15\1\26\1\13\1\25\1\12\1\24\1\15\1\11\1\16"+
    "\1\21\1\30\1\15\1\17\3\15\1\31\1\0\1\32\7\0\1\6"+
    "\u1fa2\0\1\6\1\6\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\2\3\1\4\1\5\1\4\1\6"+
    "\4\4\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\3\0\5\4\1\16\1\17\5\4\1\20\3\4\1\21"+
    "\1\4\1\22\1\23\1\24\1\4\1\25\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[49];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\174\0\76\0\233\0\272"+
    "\0\76\0\331\0\76\0\370\0\u0117\0\u0136\0\u0155\0\76"+
    "\0\76\0\76\0\76\0\76\0\u0174\0\76\0\u0193\0\u01b2"+
    "\0\u01d1\0\u01f0\0\u020f\0\u022e\0\u024d\0\u026c\0\76\0\76"+
    "\0\u028b\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\272\0\u0326\0\u0345"+
    "\0\u0364\0\272\0\u0383\0\272\0\u03a2\0\u03c1\0\u03e0\0\272"+
    "\0\272";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[49];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\1\7\1\0\1\10"+
    "\1\11\1\12\2\10\1\13\1\10\1\14\1\10\1\15"+
    "\3\10\1\16\2\10\1\17\1\10\1\20\1\21\1\22"+
    "\1\23\1\24\1\13\4\25\2\0\2\25\1\26\26\25"+
    "\42\0\1\27\3\0\1\30\1\0\3\27\1\31\14\27"+
    "\11\0\1\5\3\0\1\10\1\0\3\10\1\0\14\10"+
    "\12\0\1\6\35\0\1\10\3\0\1\10\1\0\3\10"+
    "\1\0\14\10\11\0\1\10\3\0\1\10\1\0\1\10"+
    "\1\32\1\10\1\0\14\10\11\0\1\10\3\0\1\10"+
    "\1\0\3\10\1\0\2\10\1\33\11\10\11\0\1\10"+
    "\3\0\1\10\1\0\3\10\1\0\10\10\1\34\3\10"+
    "\11\0\1\10\3\0\1\10\1\0\1\35\2\10\1\0"+
    "\14\10\11\0\1\10\3\0\1\10\1\0\3\10\1\0"+
    "\13\10\1\36\6\0\4\25\2\0\2\25\1\0\26\25"+
    "\2\0\1\37\1\30\3\0\1\30\1\0\3\30\1\0"+
    "\14\30\10\0\1\40\1\30\3\0\1\30\1\0\3\30"+
    "\1\0\14\30\10\0\1\37\37\0\1\10\3\0\1\10"+
    "\1\0\1\10\1\41\1\10\1\0\14\10\11\0\1\10"+
    "\3\0\1\10\1\0\3\10\1\0\3\10\1\42\10\10"+
    "\11\0\1\10\3\0\1\10\1\0\3\10\1\0\7\10"+
    "\1\43\4\10\11\0\1\10\3\0\1\10\1\0\3\10"+
    "\1\0\3\10\1\44\10\10\11\0\1\10\3\0\1\10"+
    "\1\0\2\10\1\45\1\0\14\10\11\0\1\10\3\0"+
    "\1\10\1\0\2\10\1\46\1\0\14\10\11\0\1\10"+
    "\3\0\1\10\1\0\3\10\1\0\4\10\1\47\7\10"+
    "\11\0\1\10\3\0\1\10\1\0\3\10\1\0\13\10"+
    "\1\50\11\0\1\10\3\0\1\10\1\0\3\10\1\0"+
    "\10\10\1\51\3\10\11\0\1\10\3\0\1\10\1\0"+
    "\3\10\1\0\7\10\1\52\4\10\11\0\1\10\3\0"+
    "\1\10\1\0\3\10\1\0\5\10\1\53\6\10\11\0"+
    "\1\10\3\0\1\10\1\0\3\10\1\0\4\10\1\54"+
    "\7\10\11\0\1\10\3\0\1\10\1\0\3\10\1\0"+
    "\4\10\1\55\7\10\11\0\1\10\3\0\1\10\1\0"+
    "\3\10\1\0\6\10\1\56\5\10\11\0\1\10\3\0"+
    "\1\10\1\0\3\10\1\0\11\10\1\57\2\10\11\0"+
    "\1\10\3\0\1\10\1\0\1\60\2\10\1\0\14\10"+
    "\11\0\1\10\3\0\1\10\1\0\3\10\1\0\10\10"+
    "\1\61\3\10\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1023];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\2\1\1\11\1\1\1\11"+
    "\4\1\5\11\1\1\1\11\3\0\5\1\2\11\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[49];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private TAParser yyparser;
  private String str;

  public TALexer(java.io.Reader r, TAParser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }
  
  public int line(){
  	return yyline;
  }
  
  public int pos(){
  	return yychar;
  }
  
  


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TALexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 108) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.err.println("Unexpected "+ yytext());
          }
        case 23: break;
        case 2: 
          { yyparser.yylval = new TAParserVal(Integer.parseInt(yytext())); return TAParser.NUM;
          }
        case 24: break;
        case 3: 
          { yyline++;
          }
        case 25: break;
        case 4: 
          { yyparser.yylval = new TAParserVal(yytext()); return TAParser.WORD;
          }
        case 26: break;
        case 5: 
          { yybegin(STR); str = "";
          }
        case 27: break;
        case 6: 
          { 
          }
        case 28: break;
        case 7: 
          { return '{';
          }
        case 29: break;
        case 8: 
          { return '}';
          }
        case 30: break;
        case 9: 
          { return '(';
          }
        case 31: break;
        case 10: 
          { return ')';
          }
        case 32: break;
        case 11: 
          { return ',';
          }
        case 33: break;
        case 12: 
          { str = yytext();
          }
        case 34: break;
        case 13: 
          { yyparser.yylval = new TAParserVal(str); yybegin(YYINITIAL); return TAParser.STRING;
          }
        case 35: break;
        case 14: 
          { yyparser.yylval = new TAParserVal(yytext().charAt(1)); return TAParser.CASE;
          }
        case 36: break;
        case 15: 
          { yyparser.yylval = new TAParserVal(yytext().substring(1, yytext().length()-1)); return TAParser.ID;
          }
        case 37: break;
        case 16: 
          { return TAParser.ROOM;
          }
        case 38: break;
        case 17: 
          { yyparser.yylval = new TAParserVal(2); return TAParser.METHOD;
          }
        case 39: break;
        case 18: 
          { yyparser.yylval = new TAParserVal(3); return TAParser.METHOD;
          }
        case 40: break;
        case 19: 
          { yyparser.yylval = new TAParserVal(0); return TAParser.METHOD;
          }
        case 41: break;
        case 20: 
          { return TAParser.SWITCH;
          }
        case 42: break;
        case 21: 
          { return TAParser.SWITCHR;
          }
        case 43: break;
        case 22: 
          { yyparser.yylval = new TAParserVal(1); return TAParser.METHOD;
          }
        case 44: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
