/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package Parsing;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>TA.flex</tt>
 */
class TALexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STR = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\40\1\32\1\41\1\41\1\31\22\0\1\12\1\0\1\5"+
    "\4\0\1\11\1\35\1\36\2\0\1\37\3\0\12\3\7\0\32\13"+
    "\1\1\1\0\1\2\1\0\1\4\1\0\2\13\1\20\1\13\1\27"+
    "\1\13\1\25\1\21\1\16\1\13\1\30\1\24\1\10\1\23\1\7"+
    "\1\22\1\13\1\6\1\14\1\17\1\26\1\13\1\15\3\13\1\33"+
    "\1\0\1\34\7\0\1\41\u1fa2\0\1\41\1\41\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\2\3\1\5\5\3"+
    "\2\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\0\10\3\1\16\1\0\10\3\1\0\1\17\6\3"+
    "\1\20\1\21\2\3\1\22\2\3\1\23\1\24\1\25"+
    "\3\3\1\26\2\3\1\27\1\30\2\3\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\104\0\314"+
    "\0\356\0\104\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba"+
    "\0\104\0\104\0\104\0\104\0\104\0\104\0\u01dc\0\104"+
    "\0\u01fe\0\u0220\0\u0242\0\u0264\0\u0286\0\u02a8\0\u02ca\0\u02ec"+
    "\0\u030e\0\u0330\0\104\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da"+
    "\0\u03fc\0\u041e\0\u0440\0\u0462\0\u0484\0\252\0\u04a6\0\u04c8"+
    "\0\u04ea\0\u050c\0\u052e\0\u0550\0\252\0\104\0\u0572\0\u0594"+
    "\0\252\0\u05b6\0\u05d8\0\u05fa\0\252\0\u061c\0\u063e\0\u0660"+
    "\0\u0682\0\252\0\u06a4\0\u06c6\0\252\0\252\0\u06e8\0\u070a"+
    "\0\252";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\1\7\1\10\1\11"+
    "\1\6\1\3\1\12\1\6\1\13\1\6\1\14\1\6"+
    "\1\15\1\6\1\16\2\6\1\17\3\6\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\12\1\0\5\27"+
    "\1\30\23\27\2\0\7\27\45\0\2\31\1\0\3\31"+
    "\1\32\1\0\16\31\14\0\1\5\1\6\1\0\3\6"+
    "\2\0\16\6\14\0\2\6\1\0\3\6\2\0\16\6"+
    "\14\0\2\6\1\0\1\6\1\33\1\6\2\0\16\6"+
    "\14\0\2\6\1\0\3\6\2\0\7\6\1\34\6\6"+
    "\14\0\2\6\1\0\3\6\2\0\2\6\1\35\13\6"+
    "\14\0\2\6\1\0\3\6\2\0\10\6\1\36\5\6"+
    "\14\0\2\6\1\0\1\6\1\37\1\6\2\0\6\6"+
    "\1\40\7\6\14\0\2\6\1\0\1\41\2\6\2\0"+
    "\16\6\14\0\2\6\1\0\1\6\1\42\1\6\2\0"+
    "\16\6\43\0\1\21\7\0\5\27\1\0\23\27\2\0"+
    "\7\27\2\0\1\43\2\31\1\0\3\31\2\0\16\31"+
    "\14\0\1\44\2\0\3\44\1\0\17\44\14\0\2\6"+
    "\1\0\1\6\1\45\1\6\2\0\16\6\14\0\2\6"+
    "\1\0\3\6\2\0\4\6\1\46\11\6\14\0\2\6"+
    "\1\0\3\6\2\0\3\6\1\47\12\6\14\0\2\6"+
    "\1\0\3\6\2\0\7\6\1\50\6\6\14\0\2\6"+
    "\1\0\3\6\2\0\10\6\1\51\5\6\14\0\2\6"+
    "\1\0\3\6\2\0\14\6\1\52\1\6\14\0\2\6"+
    "\1\0\3\6\2\0\3\6\1\53\12\6\14\0\2\6"+
    "\1\0\3\6\2\0\4\6\1\54\11\6\22\0\1\55"+
    "\33\0\2\6\1\0\2\6\1\56\2\0\16\6\14\0"+
    "\2\6\1\0\3\6\2\0\3\6\1\57\12\6\14\0"+
    "\2\6\1\0\3\6\2\0\4\6\1\60\11\6\14\0"+
    "\2\6\1\0\3\6\2\0\13\6\1\61\2\6\14\0"+
    "\2\6\1\0\3\6\2\0\4\6\1\62\11\6\14\0"+
    "\2\6\1\0\3\6\2\0\5\6\1\63\10\6\14\0"+
    "\2\6\1\0\3\6\2\0\10\6\1\64\5\6\14\0"+
    "\2\6\1\0\1\6\1\65\1\6\2\0\16\6\13\0"+
    "\1\66\42\0\2\6\1\0\1\6\1\67\1\6\2\0"+
    "\16\6\14\0\2\6\1\0\3\6\2\0\5\6\1\70"+
    "\10\6\14\0\2\6\1\0\3\6\2\0\4\6\1\71"+
    "\11\6\14\0\2\6\1\0\3\6\2\0\3\6\1\72"+
    "\12\6\14\0\2\6\1\0\3\6\2\0\15\6\1\73"+
    "\14\0\2\6\1\0\3\6\2\0\4\6\1\74\11\6"+
    "\14\0\2\6\1\0\3\6\2\0\10\6\1\75\5\6"+
    "\14\0\2\6\1\0\3\6\2\0\6\6\1\76\7\6"+
    "\14\0\2\6\1\0\3\6\2\0\10\6\1\77\5\6"+
    "\14\0\2\6\1\0\3\6\2\0\7\6\1\100\6\6"+
    "\14\0\2\6\1\0\3\6\2\0\11\6\1\101\4\6"+
    "\14\0\2\6\1\0\1\102\2\6\2\0\16\6\14\0"+
    "\2\6\1\0\3\6\2\0\13\6\1\103\2\6\14\0"+
    "\2\6\1\0\1\6\1\104\1\6\2\0\16\6\14\0"+
    "\2\6\1\0\3\6\2\0\10\6\1\105\5\6\14\0"+
    "\2\6\1\0\3\6\2\0\14\6\1\106\1\6\14\0"+
    "\2\6\1\0\3\6\2\0\3\6\1\107\12\6\14\0"+
    "\2\6\1\0\3\6\2\0\10\6\1\110\5\6\14\0"+
    "\2\6\1\0\3\6\2\0\4\6\1\111\11\6\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1836];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\2\1\1\11\6\1\6\11"+
    "\1\1\1\11\2\0\10\1\1\11\1\0\10\1\1\0"+
    "\10\1\1\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private TAParser yyparser;
  private String str;

  public TALexer(java.io.Reader r, TAParser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }
  
  public int line(){
  	return yyline;
  }
  
  public int pos(){
  	return yychar;
  }
  
  


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TALexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 116) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.err.println("Unexpected "+ yytext());
          }
        case 26: break;
        case 2: 
          { yyparser.yylval = new TAParserVal(Integer.parseInt(yytext())); return TAParser.NUM;
          }
        case 27: break;
        case 3: 
          { yyparser.yylval = new TAParserVal(yytext()); return TAParser.WORD;
          }
        case 28: break;
        case 4: 
          { yybegin(STR); str = "";
          }
        case 29: break;
        case 5: 
          { 
          }
        case 30: break;
        case 6: 
          { yyline++;
          }
        case 31: break;
        case 7: 
          { return '{';
          }
        case 32: break;
        case 8: 
          { return '}';
          }
        case 33: break;
        case 9: 
          { return '(';
          }
        case 34: break;
        case 10: 
          { return ')';
          }
        case 35: break;
        case 11: 
          { return ',';
          }
        case 36: break;
        case 12: 
          { str = yytext();
          }
        case 37: break;
        case 13: 
          { yyparser.yylval = new TAParserVal(str); yybegin(YYINITIAL); return TAParser.STRING;
          }
        case 38: break;
        case 14: 
          { yyparser.yylval = new TAParserVal(yytext().substring(1, yytext().length()-1)); return TAParser.ID;
          }
        case 39: break;
        case 15: 
          { return TAParser.ROOM;
          }
        case 40: break;
        case 16: 
          { yyparser.yylval = new TAParserVal(2); return TAParser.METHOD;
          }
        case 41: break;
        case 17: 
          { yyparser.yylval = new TAParserVal(yytext().charAt(2)); return TAParser.CASE;
          }
        case 42: break;
        case 18: 
          { yyparser.yylval = new TAParserVal(3); return TAParser.METHOD;
          }
        case 43: break;
        case 19: 
          { yyparser.yylval = new TAParserVal(0); return TAParser.METHOD;
          }
        case 44: break;
        case 20: 
          { yyparser.yylval = new TAParserVal(5); return TAParser.METHOD;
          }
        case 45: break;
        case 21: 
          { return TAParser.SWITCH;
          }
        case 46: break;
        case 22: 
          { return TAParser.SWITCHR;
          }
        case 47: break;
        case 23: 
          { yyparser.yylval = new TAParserVal(1); return TAParser.METHOD;
          }
        case 48: break;
        case 24: 
          { yyparser.yylval = new TAParserVal(4); return TAParser.METHOD;
          }
        case 49: break;
        case 25: 
          { yyparser.yylval = new TAParserVal(6); return TAParser.METHOD;
          }
        case 50: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
